# Generated by Django 5.1.2 on 2024-10-24 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('numero_documento', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='Inventario.stock')),
            ],
        ),
    ]
