# Generated by Django 5.1.2 on 2024-10-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
