# Generated by Django 5.1.2 on 2024-10-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_alter_lote_cantidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'permissions': [('can_delete_stock', 'Puede eliminar'), ('can_change_stock', 'Puede modificar'), ('can_add_stock', 'Puede agregar')]},
        ),
    ]
