# Generated by Django 5.1.2 on 2024-10-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_alter_stock_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'permissions': [('can_delete_stock', 'Puede eliminar stock'), ('can_change_stock', 'Puede modificar stock'), ('can_add_stock', 'Puede agregar stock')]},
        ),
    ]
