# Generated by Django 5.1.2 on 2024-10-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_alter_stock_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={},
        ),
    ]
