# Generated by Django 5.1.2 on 2024-10-24 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventario', '0006_alter_stock_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('tiempo', models.DateField(auto_now_add=True)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('nit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura_items', to='Ventas.factura')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_venta', to='Inventario.stock')),
            ],
        ),
    ]
