# Generated by Django 5.1.2 on 2024-10-24 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='tiempo',
            new_name='fecha',
        ),
    ]
